Add some descriptions when memory leak

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -133,7 +133,8 @@ jobs:
           NEBULA_TEST_LOGS_DIR: ${{ github.workspace }}/build
         run: |
           make RM_DIR=false ASAN=${{ steps.cmake.outputs.asan }} -C tests test
-          exit $(grep -P "SUMMARY: AddressSanitizer: \d+ byte\(s\) leaked in \d+ allocation\(s\)\." build/server_*/logs/stderr.log | wc -l)
+          res=$(grep -P "SUMMARY: AddressSanitizer: \d+ byte\(s\) leaked in \d+ allocation\(s\)\." build/server_*/logs/stderr.log | wc -l)
+          if [[ x"$res" != x"0" ]]; then echo "There some sanitizer errors, please lookup the stderr.log!"; exit 1; fi
         timeout-minutes: 15
       - name: Upload logs
         uses: actions/upload-artifact@v2
